Add fetch
chet013/Home-project-TS pull request #5
Opened 2024-02-26 14:29 UTC by chet013

2024-02-26 14:51 UTC, igooooood requested changes

2024-02-26 14:51 UTC, igooooood commented on src/api/api.jsx
> +            console.log(data);
Функция должна что-то возвращать, чтобы это что-то использовать

2024-02-26 14:51 UTC, igooooood commented on src/api/api.jsx
> +            console.log(data);
А если ошибка произойдет, как быть что делать?

2024-02-26 14:51 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
>  const postsData: Post[] = [
Данные больше не нужны, теперь мы должны отображать то, что приходит с бека

2024-02-26 14:58 UTC, chet013 commented on src/api/api.jsx
> +            console.log(data);
Я хотел обрабатывать через трай/кетч уже в самом компоненте

2024-02-26 15:07 UTC, chet013 commented on src/api/api.jsx
> +            console.log(data);
> Функция должна что-то возвращать, чтобы это что-то использовать

вот я и не понимаю, что должна мне вернуть эта функция

2024-02-28 07:07 UTC, igooooood requested changes

2024-02-28 07:07 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
> +        setLoading(true);
Давай это перенесем внутрь функции fetchData

2024-02-28 07:07 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
> +            setError(true)
Тут ошибка проставляется в true, а в какой момент она будет очищатся? И еще вопрос, а если произошла ошибка, как нам повторно бахнуть запрос?

2024-02-28 07:07 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
> +                fetchData(), 1000 /* проверка работы спинера */
👍

2024-02-29 06:52 UTC, merged