Add autor name
chet013/Home-project-TS pull request #8
Opened 2024-03-05 11:06 UTC by chet013

2024-03-05 11:27 UTC, igooooood requested changes

2024-03-05 11:27 UTC, igooooood commented on src/pages/ListingPage/ListingPage.tsx
> +                            autorName={autors.find(autor => autor.id === post.userId)?.name}
ты должен по итогу доставать это из post.autor или вроде того

2024-03-05 11:27 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
> +    const [autors, setAutors] = useState<Autors[]>([])
этого не должно быть, нам не нужны все пользователи

2024-03-05 11:27 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
> +            const autorNames = await getAutors();
вот тут после того как ты получил данные, ты должен на основе двух массивов сделать тот самый массив который будет совмещать и то и то

2024-03-05 11:27 UTC, igooooood commented on src/pages/ListingPage/ListingPageContainer.tsx
> +        autors={autors}
имя должно содержаться в постах

2024-03-05 11:27 UTC, igooooood commented on src/types.tsx
>      autorName: string,
видишь у тебя в этом типе есть поле, но ты его теперь никак не используешь, потому что в твоей реализации там ничего не лежит

2024-03-05 11:27 UTC, igooooood commented on src/types.tsx
> +export type Autors = {
тип тоже не нужен

2024-03-06 08:59 UTC, chet013 commented on src/types.tsx
> +export type Autors = {
Не могу от него отказаться, выдает ошиьки

2024-03-06 10:13 UTC, i-ukhov requested changes

2024-03-06 10:13 UTC, i-ukhov commented on src/pages/ListingPage/ListingPageContainer.tsx
> +                return post.autorName = autorNames.find((autor: Autors) => autor.id === post.userId)?.name
Способ рабочий, но как минимум тогда надо было использовать .forEach. Метод map возвращает нам новый массив в данном случае ты его никак не используешь. Разработчики стараются в методах map ничего не менять (post.autorName = autorNames.find) такая запись по факту изменяет твой массив пост дата это плохая практика. Если хочешь изменить как-то данные, то создай на основе массива новый массив не изменяя старый. Плохо это потому, что если у тебя где-то использовался старый массив а ты его изменил это может привести нас к чему-то не очень хорошему.

2024-03-06 10:13 UTC, i-ukhov commented on src/pages/ListingPage/ListingPageContainer.tsx
> +                return post.autorName = autorNames.find((autor: Autors) => autor.id === post.userId)?.name
в предыдущем комментарии я написал тебе чтобы ты создал функцию которая бы называлась подготовка данных в которую ты бы передавал 2 массива а на выходе получал свой результирующий.

2024-03-07 09:12 UTC, merged